### ISSUE TITLE
White Page of Death

### ISSUE THREAD

**Issue by mikebronner** [wpscholar/wp-skeleton#1]
Just installed, confirmed that database settings are correct, but getting blank page when trying to load.

**Comment by wpscholar** [comment]
Did you rename `sample-wp-config-local.php` to `wp-config-local.php`?  Also, if you set `WP_DEBUG` to true, you should get an error message with more details.  If you don't mind posting that, it would be helpful.  Thanks!

**Comment by mikebronner** [comment]
Turns out this might happen when using previously set up database. Starting on a new data resolved the issue. My guess is that some settings or plugins that were configured in the database, but not present in the codebase were causing an issue.

Just as a note: WP_DEBUG true didn't output anything either, and there were also no PHP errors being logged in the server logs.

**Comment by mikebronner** [comment]
@wpscholar Thanks for your quick response, I tried that before figuring out it was a database issue as well. :)

**Comment by wpscholar** [comment]
@mikebronner Got it.  Let me know if you encounter other issues or have any questions.
